"""
稳定枚举定义
"""

from enum import Enum


# ── 数据轨道 ──
class DataTrack(str, Enum):
    NATURAL = "NATURAL"
    SCENARIO = "SCENARIO"


# ── 严重度 ──
class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ── 规则类型 ──
class RuleType(str, Enum):
    DROP_THRESHOLD = "DROP_THRESHOLD"
    UPPER_THRESHOLD = "UPPER_THRESHOLD"
    LOWER_THRESHOLD = "LOWER_THRESHOLD"
    SHIFT_THRESHOLD = "SHIFT_THRESHOLD"


# ── 指标方向 ──
class MetricDirection(str, Enum):
    HIGHER_BETTER = "HIGHER_BETTER"
    LOWER_BETTER = "LOWER_BETTER"
    DEVIATION_BAD = "DEVIATION_BAD"


# ── 证据方向 ──
class EvidenceDirection(str, Enum):
    SUPPORT = "SUPPORT"
    AGAINST = "AGAINST"
    NEUTRAL = "NEUTRAL"


# ── 置信度 ──
class ConfidenceLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


# ── 可用性状态 ──
class AvailabilityStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    LABEL_NOT_MATURE = "LABEL_NOT_MATURE"
    DATA_NOT_AVAILABLE = "DATA_NOT_AVAILABLE"
    SAMPLE_TOO_SMALL = "SAMPLE_TOO_SMALL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CALCULATION_FAILED = "CALCULATION_FAILED"


# ── 告警对象类型 ──
class ObjectType(str, Enum):
    FEATURE = "FEATURE"
    MODEL = "MODEL"
    SEGMENT = "SEGMENT"
    BUSINESS = "BUSINESS"


# ── 四维维度 ──
class DimensionCode(str, Enum):
    DATA = "DATA"
    FEATURE = "FEATURE"
    MODEL = "MODEL"
    BUSINESS = "BUSINESS"


# ── D/R/C/T/I 证据类型 ──
class EvidenceType(str, Enum):
    D = "D"  # Distribution / Data      — 分布、数据质量和直接异常事实
    R = "R"  # Repair / Recovery        — 反事实修复后性能是否恢复
    C = "C"  # Conditional / Causal     — 控制变量后根因与性能的关联
    T = "T"  # Temporal                 — 原因是否先于症状出现
    I = "I"  # Importance / Dependency  — 模型是否依赖该特征或机制


# ── 任务二推荐动作 ──
class RecommendedAction(str, Enum):
    MODEL_ITERATION = "MODEL_ITERATION"
    DATA_REPAIR = "DATA_REPAIR"
    PIPELINE_REPAIR = "PIPELINE_REPAIR"
    CALIBRATION_ADJUSTMENT = "CALIBRATION_ADJUSTMENT"
    THRESHOLD_ADJUSTMENT = "THRESHOLD_ADJUSTMENT"
    CONTINUE_OBSERVATION = "CONTINUE_OBSERVATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    NO_ACTION = "NO_ACTION"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ProposalStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"


class ReviewDecision(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class TrainingPlanStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    BLOCKED = "BLOCKED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DataUsabilityStatus(str, Enum):
    USABLE = "USABLE"
    USABLE_WITH_WARNING = "USABLE_WITH_WARNING"
    UNSUPERVISED_ONLY = "UNSUPERVISED_ONLY"
    BLOCKED = "BLOCKED"


class MissingRateBand(str, Enum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    UNAVAILABLE = "UNAVAILABLE"


class QualificationGateCode(str, Enum):
    DATA_REPRODUCIBILITY = "DATA_REPRODUCIBILITY"
    TARGET_RECOVERY = "TARGET_RECOVERY"
    DISCRIMINATION = "DISCRIMINATION"
    CALIBRATION = "CALIBRATION"
    STABILITY = "STABILITY"
    SEGMENT_GOVERNANCE = "SEGMENT_GOVERNANCE"
    OOT = "OOT"


class QualificationStatus(str, Enum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class IterationExitReason(str, Enum):
    QUALIFIED = "QUALIFIED"
    NO_MODEL_TRAINING_REQUIRED = "NO_MODEL_TRAINING_REQUIRED"
    DATA_NOT_ELIGIBLE = "DATA_NOT_ELIGIBLE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    REVIEW_REJECTED = "REVIEW_REJECTED"
    MAX_BUSINESS_ROUNDS_REACHED = "MAX_BUSINESS_ROUNDS_REACHED"
    TECHNICAL_FAILURE = "TECHNICAL_FAILURE"
    QUALIFICATION_FAILED = "QUALIFICATION_FAILED"


class FailureCode(str, Enum):
    DATA_GATE_BLOCKED = "DATA_GATE_BLOCKED"
    TRAINING_TECHNICAL_FAILURE = "TRAINING_TECHNICAL_FAILURE"
    TARGET_RECOVERY_FAILED = "TARGET_RECOVERY_FAILED"
    DISCRIMINATION_FAILED = "DISCRIMINATION_FAILED"
    CALIBRATION_FAILED = "CALIBRATION_FAILED"
    STABILITY_FAILED = "STABILITY_FAILED"
    SEGMENT_GOVERNANCE_FAILED = "SEGMENT_GOVERNANCE_FAILED"
    OOT_FAILED = "OOT_FAILED"
    MANUAL_REVIEW_REJECTED = "MANUAL_REVIEW_REJECTED"
    MAX_ROUNDS_REACHED = "MAX_ROUNDS_REACHED"


# ── 部署决策 ──
class DeploymentDecision(str, Enum):
    PROMOTE = "PROMOTE"
    ADVANCE_STAGE = "ADVANCE_STAGE"
    HOLD = "HOLD"
    PAUSE_CANARY = "PAUSE_CANARY"
    REDUCE_TRAFFIC = "REDUCE_TRAFFIC"
    ROLLBACK = "ROLLBACK"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    ABORT_DEPLOYMENT = "ABORT_DEPLOYMENT"


# ── 部署阶段 ──
class DeploymentStage(str, Enum):
    OFFLINE_VALIDATION = "OFFLINE_VALIDATION"
    OOT_GATE = "OOT_GATE"
    SHADOW = "SHADOW"
    CANARY_5 = "CANARY_5"
    CANARY_20 = "CANARY_20"
    CANARY_50 = "CANARY_50"
    PRODUCTION = "PRODUCTION"


# ── 触发类型 ──
class TriggerType(str, Enum):
    SCHEDULED_TRIGGER = "SCHEDULED_TRIGGER"
    THRESHOLD_TRIGGER = "THRESHOLD_TRIGGER"
    ABNORMAL_TRIGGER = "ABNORMAL_TRIGGER"
    MANUAL_TRIGGER = "MANUAL_TRIGGER"
    DEPLOYMENT_FAILURE_ANALYSIS = "DEPLOYMENT_FAILURE_ANALYSIS"


# ── 生命周期阶段 ──
class LifecyclePhase(str, Enum):
    CREATED = "CREATED"
    MONITORING = "MONITORING"
    MONITORING_COMPLETED = "MONITORING_COMPLETED"
    NO_ALERT = "NO_ALERT"
    DIAGNOSING = "DIAGNOSING"
    DIAGNOSIS_COMPLETED = "DIAGNOSIS_COMPLETED"
    # Agent 决策阶段（LangGraph 开发路线 V1.0）
    WAITING_AGENT_DECISION = "WAITING_AGENT_DECISION"
    AGENT_DECIDING = "AGENT_DECIDING"
    DECISION_PROPOSED = "DECISION_PROPOSED"
    # 迭代/训练阶段
    ITERATING = "ITERATING"
    WAITING_FEATURE_RECONSTRUCTION = "WAITING_FEATURE_RECONSTRUCTION"
    CHALLENGER_TRAINED = "CHALLENGER_TRAINED"
    WAITING_TRAINING_CALLBACK = "WAITING_TRAINING_CALLBACK"
    # 资格验证
    OFFLINE_VALIDATING = "OFFLINE_VALIDATING"
    QUALIFICATION_COMPLETED = "QUALIFICATION_COMPLETED"
    OOT_VALIDATING = "OOT_VALIDATING"
    # 部署阶段
    WAITING_DEPLOYMENT = "WAITING_DEPLOYMENT"
    SHADOW_RUNNING = "SHADOW_RUNNING"
    CANARY_RUNNING = "CANARY_RUNNING"
    PROMOTED = "PROMOTED"
    ROLLED_BACK = "ROLLED_BACK"
    # 终态
    MANUAL_REVIEW = "MANUAL_REVIEW"
    EVENT_CLOSED = "EVENT_CLOSED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"


# ── Worker/任务状态 ──
class WorkerStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRYING = "RETRYING"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    DEAD_LETTER = "DEAD_LETTER"
    LOST = "LOST"


# ── Qdrant 同步状态 ──
class SyncStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    RETRYING = "RETRYING"
    SUCCEEDED = "SUCCEEDED"
    DEAD_LETTER = "DEAD_LETTER"
    CANCELLED = "CANCELLED"


# ── 验证步骤状态 ──
class ValidationStepStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


# ── Query Profile ──
class QueryProfileCode(str, Enum):
    EXPLORATION = "exploration"
    PRODUCTION_MONITORING = "production_monitoring"
    PRODUCTION_DIAGNOSIS = "production_diagnosis"
    AUTOMATIC_ITERATION_STRATEGY = "automatic_iteration_strategy"
    PRODUCTION_DEPLOYMENT_ADVICE = "production_deployment_advice"


# ── 向量同步事件类型 ──
class VectorSyncEventType(str, Enum):
    UPSERT_CHUNK = "UPSERT_CHUNK"
    DELETE_CHUNK = "DELETE_CHUNK"
    DELETE_DOCUMENT_VERSION = "DELETE_DOCUMENT_VERSION"
    REINDEX_DOCUMENT_VERSION = "REINDEX_DOCUMENT_VERSION"
    REBUILD_COLLECTION = "REBUILD_COLLECTION"


# ── 诊断事件状态（LangGraph 开发路线 V1.0 ──
class DiagnosisEventStatus(str, Enum):
    OPEN = "OPEN"
    WAITING_AGENT_DECISION = "WAITING_AGENT_DECISION"
    AGENT_DECIDING = "AGENT_DECIDING"
    DECISION_PROPOSED = "DECISION_PROPOSED"
    WAITING_MANUAL_REVIEW = "WAITING_MANUAL_REVIEW"
    IN_REPAIR = "IN_REPAIR"
    TRAINING = "TRAINING"
    WAITING_TRAINING_CALLBACK = "WAITING_TRAINING_CALLBACK"
    VALIDATING = "VALIDATING"
    WAITING_DEPLOYMENT = "WAITING_DEPLOYMENT"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    LEGACY_INVALID = "LEGACY_INVALID"


# ── Agent 决策动作 ──
class AgentDecisionAction(str, Enum):
    NO_ACTION = "NO_ACTION"
    CONTINUE_OBSERVATION = "CONTINUE_OBSERVATION"
    DATA_REPAIR = "DATA_REPAIR"
    PIPELINE_REPAIR = "PIPELINE_REPAIR"
    CALIBRATION_ADJUSTMENT = "CALIBRATION_ADJUSTMENT"
    THRESHOLD_ADJUSTMENT = "THRESHOLD_ADJUSTMENT"
    MODEL_ITERATION = "MODEL_ITERATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"
